title: Meghan Hatzipetro # your name (or website title) here
logo: "/images/Me.jpg?raw=true" # your photo (or logo) here
description: > 
<div>
  <i>An engineer with a knack for automation.</i>
  <br>
  My background is in Engineering with a mechanical specialization. I enjoy interactions, regardless of whether those interactions are collaborating on a project, code interacting with hardware, or exothermic... <a href="/more.html">more</a>
  VB/VBA|Python|C/C++|MATLAB|Fortran<br>
  <a href="https://www.linkedin.com/in/meghan-hatzipetro-881522b0/">Interact with me on Linked In</a> <br>
  <a href="mailto:Mhatzipetro310@g.rwu.edu?Subject=I%20saw%20your%20page" target="_top">Interact with me via Email</a><br>
  <a href="/pdf/Mhatzipetro_Resume.pdf">Download Resume</a>
<<<<<<< HEAD
=======
  </div>
  <div>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
</div>
>>>>>>> 571a6b410dc438c8c415e242a4627384300a1e47
